import type { Metadata } from "next";
import { Afacad } from "next/font/google"; // ✅ import Afacad
import "./globals.css";

import Header from "./Header";

// ✅ Load Afacad font with desired weights
const afacad = Afacad({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // add weights you need
  variable: "--font-afacad", // optional CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${afacad.variable} antialiased`} // ✅ using Afacad variable
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
